services:
  api:
    build: .
    container_name: node-scraper
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ngrok:
    image: ngrok/ngrok:latest
    command: http --authtoken ${NGROK_AUTHTOKEN} --domain ${NGROK_DOMAIN} api:3000
    depends_on:
      - api
    ports:
      - "4040:4040"
    env_file:
      - .env

volumes:
  redis_data:
